version: "3.9"
services:
  database:
    image: book_shelf_database
    container_name: book_shelf_database
    build:
      context: .
      target: book_shelf_database
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=book_shelf
    ports:
      - 5401:5432
    networks:
      - book_shelf
    profiles:
      ["book_shelf", "database"]


networks:
  book_shelf:
    name: BookShelf
